#!/usr/bin/env bash
# Write flint-extension/.env for local staging sim (:3001 / :8001).
# Usage: ./scripts/sync-extension-staging-env.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EXT_DIR="${FLINT_EXTENSION_DIR:-$ROOT/../flint-extension}"
BACKEND_ENV="$ROOT/backend/.env.staging"
OUT="$EXT_DIR/.env"

if [[ ! -d "$EXT_DIR" ]]; then
  echo "flint-extension not found at $EXT_DIR" >&2
  echo "Set FLINT_EXTENSION_DIR to your extension checkout." >&2
  exit 1
fi

API_URL="${STAGING_BACKEND_PORT:-8001}"
WEB_URL="${STAGING_FRONTEND_PORT:-3001}"
GOOGLE_CLIENT_ID=""

if [[ -f "$BACKEND_ENV" ]]; then
  # shellcheck disable=SC1090
  val="$(grep -E '^GOOGLE_CLIENT_ID=' "$BACKEND_ENV" | head -1 | cut -d= -f2- | tr -d '"' || true)"
  if [[ -n "$val" ]]; then
    GOOGLE_CLIENT_ID="$val"
  fi
fi

if [[ -z "$GOOGLE_CLIENT_ID" ]]; then
  echo "WARN: GOOGLE_CLIENT_ID not found in $BACKEND_ENV — set VITE_GOOGLE_CLIENT_ID manually." >&2
fi

cat >"$OUT" <<EOF
# Generated by smart-resume/scripts/sync-extension-staging-env.sh — local staging sim
VITE_API_BASE_URL=http://localhost:${API_URL}
VITE_WEB_APP_BASE_URL=http://localhost:${WEB_URL}
VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
EOF

echo "Wrote $OUT"
echo "Next: cd $EXT_DIR && npm run build && reload at chrome://extensions"
